# Generated by Django 4.2.3 on 2023-07-11 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha creada"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha modificada"
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha creada"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha modificada"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="Precio"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.menu"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
