# Generated by Django 4.2.3 on 2023-07-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.restaurante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="Precio"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.menu"
                    ),
                ),
            ],
        ),
    ]
