# Generated by Django 4.2.3 on 2023-07-06 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_menu_plato"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha creada",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menu",
            name="modificado",
            field=models.DateTimeField(auto_now=True, verbose_name="Fecha modificada"),
        ),
        migrations.AddField(
            model_name="plato",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha creada",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plato",
            name="modificado",
            field=models.DateTimeField(auto_now=True, verbose_name="Fecha modificada"),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha creada",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurante",
            name="modificado",
            field=models.DateTimeField(auto_now=True, verbose_name="Fecha modificada"),
        ),
    ]
