# Generated by Django 4.2.3 on 2023-07-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_menu_creado_menu_modificado_plato_creado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plato",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.menu"
            ),
        ),
    ]
