# Generated by Django 4.2.3 on 2023-08-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_plato_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha creada"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha modificada"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(max_length=200, verbose_name="User Agent"),
                ),
                ("ip", models.CharField(max_length=200, verbose_name="IP")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.menu"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
