# Generated by Django 4.2.3 on 2023-08-07 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_acceso"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="codigo",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="Codigo"),
        ),
    ]
