# Generated by Django 4.2.3 on 2023-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_menu_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="estado",
            field=models.CharField(
                choices=[("publicado", "Publicado"), ("oculto", "Oculto")],
                default="publicado",
                max_length=100,
                verbose_name="Estado",
            ),
            preserve_default=False,
        ),
    ]
