# Generated by Django 4.2.3 on 2023-11-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_menu_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="descripcion",
            field=models.TextField(default="", verbose_name="Descripción"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categoria",
            name="estado",
            field=models.CharField(
                choices=[("publicada", "Publicada"), ("oculta", "Oculta")],
                default="oculta",
                max_length=100,
                verbose_name="Estado",
            ),
        ),
    ]
