# Generated by Django 4.2.3 on 2023-11-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_categoria_descripcion_categoria_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plato",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Precio"
            ),
        ),
    ]
